### ISSUE TITLE
relation_fv requires name, breaking terraform import (forces resource deletion)

### ISSUE THREAD

**Issue by vfiftyfive** [ciscoecosystem/terraform-provider-aci#36] opened 2019-06-08 18:33 UTC
Hi,

Most of `relation_fv_` attributes expect the name of the source, as opposed to id/Dn.
When importing ACI resources to terraform, the terraform state doesn't get populated with the `name` attribute. 
As a result, after performing a `terraform plan`, one needs to set the `name` attribute of the imported resource so interpolation can happen.
But because the `name` attribute is empty in the state file, this leads to a difference between configuration and state and therefore deletion/recreation of the resource is required.

Expected behavior should be that either:
1) `Name` attribute of imported resources is added in the terraform state file
2) Relations attributes use id/Dn and not name

example: 
`terraform import aci_tenant.imported_tenant uni/tn-imported_tenant`
`terraform import aci_vrf.vrf1 uni/tn-imported_tenant/ctx-vrf1`

config file:
```
resource "aci_tenant" "imported_tenant" {
  name = ""
}

resource "aci_vrf" "vrf1" {
  name      = "vrf1"
  tenant_dn = "${aci_tenant.imported_tenant.id}"
}

resource "aci_bridge_domain" "bd1" {
  tenant_dn          = "${aci_tenant.imported_tenant.id}"
  relation_fv_rs_ctx = "${aci_vrf.vrf1.name}"
  name               = "bd1"
}
```
terraform plan output:
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
-/+ destroy and then create replacement

Terraform will perform the following actions:

  + aci_bridge_domain.bd1
      id:                          <computed>
      annotation:                  <computed>
      arp_flood:                   <computed>
      ep_clear:                    <computed>
      ep_move_detect_mode:         <computed>
      host_based_routing:          <computed>
      intersite_bum_traffic_allow: <computed>
      intersite_l2_stretch:        <computed>
      ip_learning:                 <computed>
      ipv6_mcast_allow:            <computed>
      limit_ip_learn_to_subnets:   <computed>
      ll_addr:                     <computed>
      mac:                         <computed>
      mcast_allow:                 <computed>
      multi_dst_pkt_act:           <computed>
      name:                        "bd1"
      name_alias:                  <computed>
      optimize_wan_bandwidth:      <computed>
      relation_fv_rs_ctx:          "vrf1"
      tenant_dn:                   "uni/tn-imported_tenant"
      type:                        <computed>
      unicast_route:               <computed>
      unk_mac_ucast_act:           <computed>
      unk_mcast_act:               <computed>
      v6unk_mcast_act:             <computed>
      vmac:                        <computed>

-/+ aci_vrf.vrf1 (new resource required)
      id:                          "uni/tn-imported_tenant/ctx-vrf1" => <computed> (forces new resource)
      annotation:                  "" => <computed>
      bd_enforced_enable:          "no" => <computed>
      ip_data_plane_learning:      "enabled" => <computed>
      knw_mcast_act:               "permit" => <computed>
      name:                        "" => "vrf1" (forces new resource)
      name_alias:                  "" => <computed>
      pc_enf_dir:                  "ingress" => <computed>
      pc_enf_pref:                 "enforced" => <computed>
      tenant_dn:                   "uni/tn-imported_tenant" => "uni/tn-imported_tenant"


Plan: 2 to add, 0 to change, 1 to destroy.
```
Nic

**Comment by nkatarmal-crest** [comment] 2019-06-09 03:34
@vfiftyfive I tried to reproduce the issue on my environment but i am not able to reproduce it. it seems when you import any resource you should have the resource config empty like 
```
resource "aci_vrf" "test_vrf" {}
```

then import it. After you import the resource successfully add the required parameters to it.

**Comment by nkatarmal-crest** [comment] 2019-06-10 05:44
I have pushed the fix to capic branch. If you are using that branch to build the provider please pull the latest changes from it and rebuild the provider again.

**Closed by nkatarmal-crest** 2019-06-10 05:44 UTC
Labels: enhancement
