### ISSUE TITLE
Inconsistent Behavior using this provider on Windows

### ISSUE THREAD

**Issue by kecorbin** [ciscoecosystem/terraform-provider-aci#49] opened 2019-11-21 15:11 UTC
Using this provider on windows I've experienced some issues against multiple ACI fabrics with a known good code base (from Linux/Mac) 

The most recent issue I've found is that when provisioning resources from the TF config [here](https://github.com/kecorbin/terraform-aci-demo) the resources actually get provisioned, but the creation is never completed in the TF run after hours of apply time 

```
module.tenants.aci_tenant.TESTC-tenant: Still creating... [14h54m42s elapsed]
module.tenants.aci_tenant.TESTB-tenant: Still creating... [14h54m42s elapsed]
module.tenants.aci_tenant.TESTA-tenant: Still creating... [14h54m42s elapsed]
module.tenants.aci_tenant.cisco-tenant: Still creating... [14h54m42s elapsed]
```

This is on Windows 10 Version 1809 (OS Build 17763.864)

**Comment by devarshishah3** [comment] 2019-11-29 10:20
This is the same issue as #50 . Closing this one. The root cause for both the issue is same.

**Closed by devarshishah3** 2019-11-29 10:20 UTC
